In [ ]:
import numpy as np

numbers = np.arange(=1,1000000)
squares=numbers**2

print(f"first five numbers: {squares[:5]}")


TypeError: arange() got an unexpected keyword argument 'time_start'

In [9]:
import numpy as np

A=np.array([[1,2,3],[4,5,6],[7,8,9]])
B=np.array([10,20,30])

c=A+B

print(c)

[[11 22 33]
 [14 25 36]
 [17 28 39]]


TIME.TIME


UN data website
